version: 2

sources:
  - name: fpl
    description: Tables that are sourced from FPL API.
    schema: fpl
    database: bcheye

    tables:
      - name: mini_league_gameweek_scores
        description: "Represents the scores of each mini league member for each gameweek."
        columns:
          - name: entry_id
            description: "The unique identifier for each mini league member."
          - name: league_id
            description: "The unique identifier for the mini league."
          - name: gameweek
            description: "The gameweek number."
          - name: points
            description: "The points scored by the mini league member in that gameweek."
      - name: mini_league_entries
        description: "Represents the entries in each mini league."
        columns:
          - name: entry_id
            description: "The unique identifier for each mini league member."
          - name: league_id
            description: "The unique identifier for the mini league."
          - name: player_name
            description: "The name of the mini league member."
          - name: player_team
            description: "The team of the mini league member."